(define (domain pick-and-place)
  (:requirements :strips :equality)
  (:predicates
    (Conf ?q)
    (Arm ?arm)
    (Object ?obj)
    (Picked ?obj)
    (ArmEmpty ?arm)
    (Placeable ?obj)
    ; Fluent predicates
    (AtConf ?obj ?q)
  )
  (:action pick
    :parameters (?arm ?arm_pos ?obj ?obj_pos)
    :precondition (and (ArmEmpty ?arm))
    :effect (and (not (ArmEmpty ?arm))
                 (Picked ?obj))
  )
  (:action move_and_place
    :parameters (?arm ?obj ?obj_pos ?goal)
    :precondition (and (Picked ?obj) (Placeable ?obj))
    :effect (and (ArmEmpty ?arm)
                 (not (Picked ?obj))
                 (AtConf ?obj ?goal))
  )
)
