(define (domain pick-and-place)
  (:requirements :strips :equality)
  (:predicates
    (Conf ?q)
    (Arm ?arm)
    (Object ?obj)
    (ArmEmpty ?arm)
    (Movable ?obj)
    ; Fluent predicates
    (AtConf ?obj ?q)
    (ArmPos ?arm ?q)
  )
  (:action pick
    :parameters (?arm ?obj_pos)
    :precondition (and (ArmEmpty ?arm))
    :effect (and (not (ArmEmpty ?arm))
                 (ArmPos ?arm ?obj_pos))
  )
  (:action move_and_place
    :parameters (?arm ?obj ?obj_pos ?goal)
    :precondition (and (AtConf ?obj ?obj_pos)
                       (ArmPos ?arm ?obj_pos)
                       (Movable ?obj))
    :effect (and (ArmEmpty ?arm)
                 (not (ArmPos ?arm ?obj_pos))
                 (ArmPos ?arm ?goal)
                 (not (AtConf ?obj ?obj_pos))
                 (AtConf ?obj ?goal))
  )
)
