(define (stream pick-and-place)
  (:stream find-motion
    :inputs (?obj ?start ?end)
    :fluents (AtConf)
    :domain (and (Object ?obj) (ObjectPose ?start) (ObjectPose ?end))
    :outputs ()
    :certified (Movable ?obj ?start ?end)
  )
  (:stream find-motion-each
    :inputs (?obstacle ?obstacle_pos ?start ?end)
    :domain (and (Object ?obstacle) (ObjectPose ?obstacle_pos) (ObjectPose ?start) (ObjectPose ?end))
    :outputs ()
    :certified (MovableEach ?obstacle ?obstacle_pos ?start ?end)
  )
)
