(define (domain pick-and-place)
  (:requirements :strips :equality)
  (:predicates
    (Conf ?q)
    (Arm ?arm)
    (Object ?obj)
    (ArmEmpty ?arm)
    (Movable ?obj ?start ?end)
    (ObjectPose ?p)
    (Picked ?obj)
    (Path ?path ?start_joint ?goal_pos)
    ; Fluent predicates
    (AtConf ?obj ?q)
    (ArmPos ?arm ?q)
  )
  (:action pick
    :parameters (?arm ?arm_pos ?obj ?obj_pos ?path)
    :precondition (and (ArmEmpty ?arm) (Object ?obj) (ObjectPose ?obj_pos) (Path ?path ?arm_pos ?obj_pos))
    :effect (and (not (ArmEmpty ?arm))
                 (ArmPos ?arm ?obj_pos)
                 (Picked ?obj))
  )
  (:action move_and_place
    :parameters (?arm ?obj ?obj_pos ?goal)
    :precondition (and (AtConf ?obj ?obj_pos)
                       (ArmPos ?arm ?obj_pos)
                       (Movable ?obj ?obj_pos ?goal)
                       (ObjectPose ?obj_pos)
                       (ObjectPose ?goal))
    :effect (and (ArmEmpty ?arm)
                 (not (ArmPos ?arm ?obj_pos))
                 (ArmPos ?arm ?goal)
                 (not (AtConf ?obj ?obj_pos))
                 (AtConf ?obj ?goal))
  )
)
